# GUARDIAN VERTEX AI - Configuration Cloud

# Configuration Vertex AI
project_id: "guardian-ai-urgence"
region: "europe-west1"
zone: "europe-west1-b"

# Modèles et endpoints
models:
  gemini:
    model_name: "gemini-1.5-flash"
    endpoint_name: "guardian-gemini-endpoint"
    machine_type: "n1-standard-2"
    min_replica_count: 1
    max_replica_count: 3
    
  speech:
    model_name: "speech-to-text"
    language_code: "fr-FR"
    encoding: "LINEAR16"
    sample_rate: 16000

# Configuration base de données
database:
  type: "firestore"
  collection_emergency_logs: "emergency_logs"
  collection_user_profiles: "user_profiles" 
  collection_alert_history: "alert_history"

# Configuration alertes
alerts:
  email:
    sender: "guardian@guardian-ai-urgence.iam.gserviceaccount.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    
  sms:
    service: "twilio"
    webhook_url: "/sms-webhook"
    
  whatsapp:
    api_version: "v17.0"
    webhook_verify_token: "guardian_whatsapp_token"

# Configuration monitoring
monitoring:
  enable_logging: true
  log_level: "INFO"
  enable_metrics: true
  enable_tracing: true
  
  metrics:
    - name: "emergency_requests_total"
      type: "counter"
    - name: "response_latency_seconds"  
      type: "histogram"
    - name: "urgency_level_distribution"
      type: "histogram"

# Configuration sécurité
security:
  enable_authentication: true
  cors_origins: 
    - "https://guardian-web-app.com"
    - "https://localhost:3000"  # Développement
  rate_limiting:
    requests_per_minute: 60
    requests_per_hour: 1000
    
# Configuration cache
cache:
  type: "redis"
  ttl_seconds: 300
  max_memory: "128mb"

# Variables d'environnement
environment:
  development:
    debug: true
    log_level: "DEBUG"
    
  production:
    debug: false
    log_level: "INFO"
    enable_ssl: true